"""add circuit breaker persistence columns to bot_state

Revision ID: 4b8a822a475b
Revises: a0f5ebc23690
Create Date: 2026-07-09 07:34:48.209745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8a822a475b'
down_revision: Union[str, Sequence[str], None] = 'a0f5ebc23690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE (manual adjustment): the autogenerated `nullable=False` column
    # needs a server_default so `ADD COLUMN` succeeds against a table that
    # already has row(s) (e.g. the singleton bot_state row seeded by
    # get_or_create_bot_state()) -- both SQLite and Postgres reject a
    # NOT NULL column with no default on a non-empty table. Defaulting to
    # "not tripped" is also the correct backfill value: a pre-existing row
    # predates this feature and was never actually tripped.
    op.add_column(
        'bot_state',
        sa.Column(
            'circuit_breaker_tripped',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('0'),
        ),
    )
    op.add_column('bot_state', sa.Column('circuit_breaker_reason', sa.String(length=1024), nullable=True))
    op.add_column('bot_state', sa.Column('circuit_breaker_tripped_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_state', 'circuit_breaker_tripped_at')
    op.drop_column('bot_state', 'circuit_breaker_reason')
    op.drop_column('bot_state', 'circuit_breaker_tripped')
    # ### end Alembic commands ###
